# Generated by Django 5.2.17 on 2026-08-07 19:09

import apps.accounts.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rol', to='auth.group')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=150, unique=True, verbose_name='nombre_usuario')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='telefono')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='accounts.rol')),
            ],
            options={
                'db_table': 'empleado',
            },
            managers=[
                ('objects', apps.accounts.models.EmpleadoManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ultimo_salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vigente', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salarios', to='accounts.rol')),
            ],
            options={
                'db_table': 'salario',
            },
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='empleado_email_lower_unique'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('telefono'), condition=models.Q(('telefono__isnull', False)), name='empleado_telefono_lower_unique'),
        ),
        migrations.AddConstraint(
            model_name='salario',
            constraint=models.CheckConstraint(condition=models.Q(('salario_actual__gte', 0)), name='salario_actual_positivo'),
        ),
        migrations.AddConstraint(
            model_name='salario',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('empleado',), name='uniq_salario_vigente_por_empleado'),
        ),
    ]
