# Generated by Django 5.2.17 on 2026-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_control',
            field=models.CharField(blank=True, help_text='Formato fiscal: 00-NNNNN (auto-generado)', max_length=10, verbose_name='Número de control'),
        ),
    ]
