# Generated by Django 5.2.17 on 2026-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_backfill_numero_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.CharField(blank=True, choices=[('devolucion', 'Devolución al cliente'), ('falta_resultado', 'Falta de resultado'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion_otro',
            field=models.TextField(blank=True, verbose_name='Especificar motivo'),
        ),
    ]
