# Generated by Django 5.2.17 on 2026-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_motivo_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tasa al emitir (Bs/$)'),
        ),
    ]
