# Generated by Django 5.2.17 on 2026-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='LAB CLINICO', max_length=150)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('lema', models.CharField(blank=True, max_length=120)),
                ('bioanalista_nombre', models.CharField(blank=True, max_length=120, verbose_name='Bioanalista para firma')),
                ('bioanalista_registro', models.CharField(blank=True, max_length=40, verbose_name='Nro de registro del bioanalista')),
            ],
            options={
                'verbose_name': 'Datos del laboratorio',
                'verbose_name_plural': 'Datos del laboratorio',
            },
        ),
    ]
