# Generated by Django 5.2.17 on 2026-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslaboratorio',
            name='simbolo_moneda',
            field=models.CharField(default='Bs.', max_length=5),
        ),
    ]
