# Generated by Django 5.2.17 on 2026-08-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datoslaboratorio_simbolo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslaboratorio',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se muestra en el encabezado de reportes y facturas en PDF', null=True, upload_to='logo/', verbose_name='Logo del laboratorio (PNG o JPG)'),
        ),
    ]
