# Generated by Django 5.2.17 on 2026-08-17 14:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logo_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='logo',
            field=models.FileField(blank=True, help_text='Se muestra en el encabezado de reportes y facturas en PDF', null=True, upload_to='logo/', validators=[apps.core.models.validar_logo], verbose_name='Logo del laboratorio (PNG, JPG o SVG)'),
        ),
    ]
