# Generated by Django 5.2.17 on 2026-09-05 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_firma_sello'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tasa (Bs por $)')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='firma_imagen',
            field=models.ImageField(blank=True, help_text='Se imprime sobre la línea de firma en los PDF', null=True, upload_to='firmas/', verbose_name='Firma del bioanalista (PNG transparente)'),
        ),
        migrations.AlterField(
            model_name='datoslaboratorio',
            name='sello_imagen',
            field=models.ImageField(blank=True, help_text='Se imprime junto a la firma en los PDF', null=True, upload_to='sellos/', verbose_name='Sello del laboratorio (PNG transparente)'),
        ),
    ]
