# Generated by Django 5.2.17 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tasacambio_alter_datoslaboratorio_firma_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(default='LabClin', max_length=120)),
                ('wa_prefijo', models.CharField(default='58', max_length=5, verbose_name='Prefijo de pais (WhatsApp)')),
                ('plantilla_whatsapp', models.TextField(default='Hola {nombre} 👋 le saluda {clinica}. Le informamos que su resultado de {servicio} esta disponible. Por favor comuniquese con el laboratorio.')),
            ],
            options={
                'verbose_name': 'Configuracion del laboratorio',
                'verbose_name_plural': 'Configuracion del laboratorio',
            },
        ),
    ]
