# Generated by Django 5.2.17 on 2026-08-07 19:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resumen_detalle',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('procesando', 'Procesando'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='abierto', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('bioanalista', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'rol__nombre': 'bioanalista'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expediente',
                'permissions': [('crear_orden_lab', 'Crear orden de laboratorio')],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('principal', models.BooleanField(default=False)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_medicos', to='patients.expediente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_medicos', to='doctors.medico')),
            ],
            options={
                'db_table': 'expediente_medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('ci', models.CharField(blank=True, max_length=30, null=True, verbose_name='CI')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paciente',
                'permissions': [('crear_paciente', 'Crear paciente')],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='paciente_apellid_ee766d_idx'), models.Index(fields=['ci'], name='paciente_ci_13f149_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('ci'), condition=models.Q(('ci__isnull', False)), name='paciente_ci_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('telefono'), condition=models.Q(('telefono__isnull', False)), name='paciente_telefono_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='paciente_email_lower_unique')],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='patients.paciente'),
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes', to='patients.paciente')),
            ],
            options={
                'db_table': 'resumen',
            },
        ),
    ]
