# Generated by Django 5.2.17 on 2026-08-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendetalle',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumen_detalles', to='results.resultado'),
        ),
        migrations.AddField(
            model_name='resumendetalle',
            name='resumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='patients.resumen'),
        ),
        migrations.AddConstraint(
            model_name='expedientemedico',
            constraint=models.UniqueConstraint(fields=('expediente', 'medico'), name='uniq_expediente_medico'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['paciente', 'estado'], name='expediente_pacient_69e983_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['fecha_creacion'], name='expediente_fecha_c_d08b00_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumendetalle',
            constraint=models.UniqueConstraint(fields=('resumen', 'resultado'), name='uniq_resumen_resultado'),
        ),
    ]
