# Generated by Django 5.2.17 on 2026-09-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_recalcular_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representados', to='patients.paciente', verbose_name='Representante legal'),
        ),
    ]
