# Generated by Django 5.2.17 on 2026-08-07 19:15

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('valores_ref', models.TextField(blank=True)),
                ('perfil', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'examen',
                'indexes': [models.Index(fields=['nombre_completo'], name='examen_nombre__72f05a_idx'), models.Index(fields=['perfil'], name='examen_perfil_6190cb_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre_completo'), name='examen_nombre_lower_unique')],
            },
        ),
        migrations.CreateModel(
            name='CostoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='exams.examen')),
            ],
            options={
                'db_table': 'costo_examen',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('examen',), name='uniq_costo_activo_por_examen')],
            },
        ),
    ]
