# Generated by Django 5.2.17 on 2026-08-07 19:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('ci', models.CharField(blank=True, max_length=30, null=True, verbose_name='CI / matrícula')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_fecha_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medico',
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='medico_apellid_ad8a56_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('ci'), condition=models.Q(('ci__isnull', False)), name='medico_ci_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('telefono'), condition=models.Q(('telefono__isnull', False)), name='medico_telefono_lower_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='medico_email_lower_unique')],
            },
        ),
    ]
